- name: maven install
  ansible.builtin.import_role:
    name: common
    from_tasks: maven

- name: setup app
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-app
  
- name: install dependencies
  ansible.builtin.command: mvn clean package
   args:
     chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: load mysql schema
  ansible.builtin.import_role:
    name: common
    from_tasks: load-mysql-schema

- name: start the application
  ansible.builtin.import_role:
    name: common
    from_tasks: systemd-setup

