  - name: install python
    ansible.builtin.import_role:
      name: common
      from_tasks: python
  
  - name: setup application
    ansible.builtin.import_role:
      name: common
      from_tasks: setup-app
 

  - name: Install dependencies
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app
  
    
  - name: systemd setup
    ansible.builtin.import_role:
      name: common
      from_tasks: systemd-setup


