- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
      src: H:\devopstools\repos\ansible-roboshop-role\roles\common\file\mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
      remote_src: yes

- name: Install MongoDB
  ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

- name: load {{component}} data
  ansible.builtin.command: mongo --host mongodb.saidev.world < /app/schema/{{component}}.js